import { createFileRoute, useNavigate } from "@tanstack/react-router";
import { useEffect, useMemo, useState } from "react";
import { cartStore, useCartItems, isLocked, lockExpiresAt, formatLockRemaining } from "~/lib/cart";
import { getProduct } from "~/lib/catalogue";
import { computePrice } from "~/config/pricing";
import { getRates } from "~/config/rates";
import { shippingFor } from "~/config/cart";
import { couponDiscount, validateCoupon, type Coupon } from "~/config/coupons";
import { formatINR, formatDateTime } from "~/lib/format";
import { newOrderId, ordersStore, type Order } from "~/lib/orders";
import { payOrder, PAYMENT_GATEWAY, isPaymentConfigured, type PaymentMethod } from "~/lib/payment";
import { pageHead } from "~/lib/seo";
export const Route=createFileRoute("/checkout")({head:()=>pageHead({title:"Checkout — Shri Madhav Jewellers",description:"Secure checkout with locked jewellery rates.",path:"/checkout"}),component:Checkout});
type Form={name:string;phone:string;email:string;address:string;city:string;state:string;pin:string;instructions:string;billingSame:boolean};
const blank:Form={name:"",phone:"",email:"",address:"",city:"",state:"",pin:"",instructions:"",billingSame:true};
function Checkout(){const items=useCartItems(); const nav=useNavigate(); const [step,setStep]=useState(1); const [form,setForm]=useState(blank); const [errors,setErrors]=useState<string[]>([]); const [code,setCode]=useState(""); const [coupon,setCoupon]=useState<Coupon>(); const [couponError,setCouponError]=useState(""); const [method,setMethod]=useState<PaymentMethod>("upi"); const [done,setDone]=useState(false); const [now,setNow]=useState(0); const [repriceNotice,setRepriceNotice]=useState(false); const [paymentConfigured,setPaymentConfigured]=useState(false); const [placing,setPlacing]=useState(false); const [paymentError,setPaymentError]=useState("");
 // Keep the first render identical to SSR: Date.now() must not participate in
 // render-time markup, otherwise React abandons hydration before binding events.
 useEffect(()=>{setNow(Date.now()); const timer=window.setInterval(()=>setNow(Date.now()),1000); void isPaymentConfigured().then(setPaymentConfigured); return()=>window.clearInterval(timer)},[]);
 useEffect(()=>{if(!items.length&&!done){nav({to:"/catalogue"});return} const result=cartStore.repriceExpired(); if(result.repriced.length)setRepriceNotice(true)},[items.length,nav,done]);
 const lines=useMemo(()=>items.map(item=>{const p=getProduct(item.productId)!; const b=computePrice({ratePerGram:item.lockedRate,weightGrams:p.weightGrams,makingCharge:p.makingCharge}); return {item,p,b,offer:(b.total*(p.offerPercent||0)/100)};}),[items]);
 const metal=lines.reduce((a,l)=>a+l.b.metalValue*l.item.qty,0), making=lines.reduce((a,l)=>a+l.b.makingCharge*l.item.qty,0), gst=lines.reduce((a,l)=>a+l.b.gst*l.item.qty,0), offers=lines.reduce((a,l)=>a+l.offer*l.item.qty,0); const base=Math.max(0,metal+making+gst-offers); const discount=couponDiscount(coupon,base); const ship=shippingFor(base-discount).fee; const total=base-discount+ship;
 function validate(){const e:string[]=[]; if(form.name.trim().length<2)e.push("Enter your full name."); if(!/^[6-9]\d{9}$/.test(form.phone.replace(/\D/g,"")))e.push("Enter a valid 10-digit Indian mobile number."); if(!/^\S+@\S+\.\S+$/.test(form.email))e.push("Enter a valid email address."); if(form.address.trim().length<8)e.push("Enter your delivery address."); if(!form.city.trim())e.push("Enter your city."); if(!form.state.trim())e.push("Enter your state."); if(!/^\d{6}$/.test(form.pin))e.push("Enter a valid 6-digit PIN code."); setErrors(e); return !e.length; }
 function apply(){const r=validateCoupon(code,base); if(r.error){setCoupon(undefined);setCouponError(r.error)}else{setCoupon(r.coupon);setCouponError("Coupon applied successfully.")}}
 async function place(){if(placing)return; if(!validate()) {setStep(1);return}; setPaymentError(""); setPlacing(true); const order:Order={id:newOrderId(),createdAt:new Date().toISOString(),items,amounts:{metal,making,gst,offers,coupon:discount,shipping:ship,subtotal:base,total},couponCode:coupon?.code,customer:form,payment:{method,status:"pending"},status:"awaiting-payment"}; // Persist before opening the hosted page: Cashfree may navigate away before
// checkout() settles, and an order must never be lost in that window.
ordersStore.save(order);
const result=await payOrder(order,method); order.payment.status=result.status; order.status=result.status==="confirmed"?"payment-confirmed":"awaiting-payment";ordersStore.save(order);cartStore.clear();setDone(true);if(result.error)setPaymentError(result.error);nav({to:"/order/$id",params:{id:order.id}})}
 const set=(k:keyof Form,v:string|boolean)=>setForm(x=>({...x,[k]:v}));
 if(!items.length||done)return null; return <main className="bg-ivory"><section className="mx-auto max-w-6xl px-5 py-12 md:px-8"><p className="eyebrow">Secure purchase</p><h1 className="mt-3 text-5xl text-ink">Complete your order</h1><div className="mt-8 grid gap-10 lg:grid-cols-[1.35fr_.65fr]"><div><div className="mb-8 grid grid-cols-3 gap-2" aria-label="Checkout steps">{["Contact & delivery","Order review","Payment"].map((x,i)=><button key={x} onClick={()=>i+1<step&&setStep(i+1)} className={`border-b-2 pb-3 text-left text-xs uppercase tracking-widest ${step===i+1?"border-gold text-ink":"border-line text-muted"}`}>{i+1}. {x}</button>)}</div>{errors.length>0&&<div role="alert" aria-live="polite" className="mb-5 rounded border border-red-200 bg-red-50 p-4 text-sm text-red-800">{errors.map(e=><div key={e}>{e}</div>)}</div>}
 {step===1&&<div className="space-y-4"> <h2 className="text-3xl">Where shall we deliver?</h2><div className="grid gap-4 sm:grid-cols-2">{([['name','Full name'],['phone','Mobile number'],['email','Email address'],['city','City'],['state','State'],['pin','PIN code']] as const).map(([k,l])=><label key={k} className="text-sm text-ink-soft">{l}<input className="field mt-1" value={form[k] as string} onChange={e=>set(k,e.target.value)} /></label>)}</div><label className="block text-sm text-ink-soft">Address line<input className="field mt-1" value={form.address} onChange={e=>set('address',e.target.value)} /></label><label className="block text-sm text-ink-soft">Delivery instructions <span className="text-muted">(optional)</span><textarea className="field mt-1" rows={2} value={form.instructions} onChange={e=>set('instructions',e.target.value)} /></label><label className="flex gap-2 text-sm"><input type="checkbox" checked={form.billingSame} onChange={e=>set('billingSame',e.target.checked)}/> Billing address same as delivery</label><p className="border-l-2 border-gold bg-gold-pale/20 p-3 text-sm text-muted">Guest checkout is ready. Create an account to track orders (coming next release).</p><button className="btn btn-gold" onClick={()=>validate()&&setStep(2)}>Continue to review</button></div>}
 {step===2&&<div><h2 className="text-3xl">Review your pieces</h2><div className="mt-5 space-y-3">{lines.map(l=><div key={l.item.productId} className="flex justify-between border-b border-line pb-3 text-sm"><div><b>{l.p.name}</b><div className="text-muted">Qty {l.item.qty} · locked rate {formatINR(l.item.lockedRate)}/g</div><div className={isLocked(l.item)?"text-gold-deep":"text-red-700"}>{isLocked(l.item)?`Rate locked · ${formatLockRemaining(Math.max(0,lockExpiresAt(l.item).getTime()-now))} remaining`:`Lock expired — reprice in cart before placing`}</div></div><span>{formatINR(l.b.total*l.item.qty)}</span></div>)}</div><a href="/cart" className="mt-4 inline-block text-sm text-gold-deep underline">Change quantities in bag</a><div className="mt-6 flex gap-2"><input className="field" placeholder="Coupon code" value={code} onChange={e=>setCode(e.target.value)} /><button className="btn btn-outline" onClick={apply}>Apply</button></div>{couponError&&<p className="mt-2 text-sm text-muted" role="status">{couponError}</p>}<button className="btn btn-gold mt-7" onClick={()=>setStep(3)}>Continue to payment</button></div>}
 {step===3&&<div><h2 className="text-3xl">Payment method</h2><p className="mt-2 text-sm text-muted">{paymentConfigured ? `Pay securely via ${PAYMENT_GATEWAY.name}.` : "Payments are currently being connected…"}</p><div className="mt-6 space-y-3">{([['upi','UPI'],['card','Credit & Debit Card'],['netbanking','Net Banking'],['wallet','Wallet']] as [PaymentMethod,string][]).map(([v,l])=><label key={v} className="flex items-center gap-3 rounded border border-line bg-white p-4"><input type="radio" name="method" checked={method===v} onChange={()=>setMethod(v)}/>{l}</label>)}</div>{paymentError&&<div role="alert" className="mt-6 rounded border border-red-300 bg-red-50 p-4 text-sm text-red-800">{paymentError}</div>}{paymentConfigured ? <div className="mt-6 rounded border border-gold/40 bg-gold-pale/20 p-4 text-sm text-ink-soft">Sandbox mode — use Cashfree test cards / test UPI provided by the Cashfree dashboard.</div> : <div className="mt-6 rounded border border-gold/40 bg-gold-pale/20 p-4 text-sm text-ink-soft">Your order will be saved as <b>pending payment</b> until the secure gateway is connected. No payment is being simulated.</div>}<button disabled={placing} className="btn btn-gold mt-7 disabled:opacity-60" onClick={place}>{placing ? "Opening secure checkout…" : `Place order · ${formatINR(total)}`}</button></div>}</div><aside className="h-fit rounded-xl border border-line bg-white p-6"><h2 className="text-2xl">Order summary</h2><Summary label="Metal value (locked rates)" value={metal}/><Summary label="Making charges" value={making}/><Summary label="GST (3%)" value={gst}/>{offers>0&&<Summary label="Offer discount" value={-offers}/>} {discount>0&&<Summary label={`Coupon ${coupon?.code}`} value={-discount}/>}<Summary label={ship?"Shipping":"Free insured shipping"} value={ship}/><div className="mt-4 flex justify-between border-t border-line pt-4 text-xl"><b>Total payable</b><b>{formatINR(total)}</b></div><p className="mt-3 text-xs text-muted">Rates are locked per item. Expired locks are refreshed before payment.</p></aside></div></section></main>}
function Summary({label,value}:{label:string;value:number}){return <div className="mt-3 flex justify-between text-sm text-ink-soft"><span>{label}</span><span>{value<0?"− ":""}{formatINR(Math.abs(value))}</span></div>}
