import { useEffect, useMemo, useState } from "react";
import { categories, getCategory } from "~/lib/catalogue";
import { computePrice, rateFor } from "~/config/pricing";
import { getRates } from "~/config/rates";
import { products, type Product } from "~/lib/catalogue";
import { formatINR } from "~/lib/format";
import { ProductCard } from "./ProductCard";

type Props = { categorySlug?: string; searchMode?: boolean };
const read = () => new URLSearchParams(window.location.search);
const multi = (p: URLSearchParams, key: string) => p.get(key)?.split(",").filter(Boolean) ?? [];
function price(p: Product) { const r=rateFor(p.metal,p.purity,getRates()); return computePrice({ratePerGram:r,weightGrams:p.weightGrams,makingCharge:p.makingCharge}).total * (1-(p.offerPercent??0)/100); }
function matches(p: Product, q: string) { const c=getCategory(p.category); return [p.name,p.category,c?.name,p.metal,p.purity,p.occasion,p.gender,...p.tags].join(" ").toLowerCase().includes(q.toLowerCase()); }

export function CatalogueView({ categorySlug, searchMode=false }: Props) {
  const [params,setParams] = useState(() => read()); const [mobile,setMobile]=useState(false); const [visible,setVisible]=useState(24);
  useEffect(()=>{ const fn=()=>setParams(read()); addEventListener("popstate",fn); return()=>removeEventListener("popstate",fn)},[]);
  const update=(key:string,value:string|string[])=>{ const p=new URLSearchParams(params); if(Array.isArray(value)){value.length?p.set(key,value.join(",")):p.delete(key)} else value?p.set(key,value):p.delete(key); history.pushState({},"",`${location.pathname}?${p}`); setParams(p); setVisible(24); };
  const q=params.get("q")??""; const base=categorySlug?products.filter(p=>p.category===categorySlug):products;
  const filtered=useMemo(()=>base.filter(p=>{
    if(searchMode&&q&&!matches(p,q)) return false;
    const cats=multi(params,"category"), metals=multi(params,"metal"), purities=multi(params,"purity"), genders=multi(params,"gender"), occasions=multi(params,"occasion");
    if(cats.length&&!cats.includes(p.category)||metals.length&&!metals.includes(p.metal)||purities.length&&!purities.includes(p.purity)||genders.length&&!genders.includes(p.gender)||occasions.length&&!occasions.includes(p.occasion)) return false;
    if(params.get("stock")==="1"&&!p.inStock||params.get("new")==="1"&&!p.isNew||params.get("best")==="1"&&!p.isBestSeller||params.get("offers")==="1"&&!p.offerPercent) return false;
    const min=Number(params.get("min")||0), max=Number(params.get("max")||Infinity); return price(p)>=min&&price(p)<=max;
  }).sort((a,b)=>{const s=params.get("sort"); if(s==="low")return price(a)-price(b);if(s==="high")return price(b)-price(a);if(s==="new")return Number(b.isNew)-Number(a.isNew);return Number(b.isBestSeller)-Number(a.isBestSeller)}),[base,params,q,searchMode]);
  const clear=()=>{ const p=new URLSearchParams(); if(categorySlug)p.set("category",categorySlug); if(searchMode&&q)p.set("q",q); history.pushState({},"",`${location.pathname}?${p}`);setParams(p);setVisible(24)};
  const toggle=(key:string,val:string)=>{const a=multi(params,key);update(key,a.includes(val)?a.filter(x=>x!==val):[...a,val])};
  const title=searchMode?(q?`Search results for “${q}”`:"Search the collection"):categorySlug?(getCategory(categorySlug)?.name??"Category"):"The Collection";
  const Filter=()=> <aside className={`${mobile?"fixed inset-0 z-40 bg-ivory p-6 overflow-auto":"hidden lg:block"} lg:w-64 shrink-0`}><div className="flex justify-between"><p className="eyebrow">Refine</p><button className="text-xs text-gold-deep" onClick={clear}>Clear all</button></div>{([["metal",["gold","silver"]],["purity",["24k","22k","18k","925"]],["gender",["women","men","unisex"]],["occasion",["bridal","everyday","festive","office","gifting"]]] as Array<[string, string[]]>).map(([key,vals])=><fieldset key={key} className="mt-6"><legend className="text-sm font-medium capitalize text-ink">{key}</legend>{(vals as string[]).map(v=><label key={v} className="mt-2 flex items-center gap-2 text-sm text-muted"><input type="checkbox" checked={multi(params,key as string).includes(v)} onChange={()=>toggle(key as string,v)} /> <span className="capitalize">{v}</span></label>)}</fieldset>)}{!categorySlug&&!searchMode&&<fieldset className="mt-6"><legend className="text-sm font-medium text-ink">Category</legend>{categories.map(c=><label key={c.slug} className="mt-2 flex items-center gap-2 text-sm text-muted"><input type="checkbox" checked={multi(params,"category").includes(c.slug)} onChange={()=>toggle("category",c.slug)}/>{c.name}</label>)}</fieldset>}<fieldset className="mt-6"><legend className="text-sm font-medium text-ink">Availability</legend>{[["stock","In stock only"],["new","New arrivals"],["best","Best sellers"],["offers","Offers"]].map(([k,l])=><label key={k} className="mt-2 flex items-center gap-2 text-sm text-muted"><input type="checkbox" checked={params.get(k)==="1"} onChange={()=>update(k,params.get(k)==="1"?"":"1")}/>{l}</label>)}</fieldset>{mobile&&<button className="btn btn-dark mt-8 w-full" onClick={()=>setMobile(false)}>View {filtered.length} results</button>}</aside>;
  return <main className="bg-ivory"><section className="bg-cream px-4 py-14 sm:px-6 lg:px-8"><div className="mx-auto max-w-7xl"><p className="eyebrow">Yogesh Jewellers · {filtered.length} pieces</p><h1 className="mt-3 font-display text-5xl text-ink">{title}</h1><p className="mt-3 max-w-xl text-muted">Explore considered pieces, priced transparently from today’s live metal rates.</p>{searchMode&&<div className="mt-7 max-w-2xl"><input autoFocus defaultValue={q} onKeyDown={e=>{if(e.key==="Enter")update("q",(e.target as HTMLInputElement).value)}} placeholder="Search rings, chains, coins…" className="w-full rounded-full border border-line bg-white px-5 py-3 outline-none focus:border-gold"/></div>}</div></section><div className="mx-auto flex max-w-7xl gap-8 px-4 py-10 sm:px-6 lg:px-8"><Filter/><section className="min-w-0 flex-1"><div className="mb-7 flex flex-wrap items-center justify-between gap-3"><button className="btn btn-outline lg:hidden" onClick={()=>setMobile(true)}>Filters</button><span className="text-sm text-muted">Showing {Math.min(visible,filtered.length)} of {filtered.length}</span><select aria-label="Sort products" value={params.get("sort")??"relevance"} onChange={e=>update("sort",e.target.value)} className="rounded-full border border-line bg-white px-4 py-2 text-sm"><option value="relevance">Relevance</option><option value="low">Price: low to high</option><option value="high">Price: high to low</option><option value="new">Newest</option></select></div>{filtered.length?<><div className="grid grid-cols-1 gap-5 sm:grid-cols-2 xl:grid-cols-3">{filtered.slice(0,visible).map(p=><ProductCard key={p.id} product={p}/>)}</div>{visible<filtered.length&&<button className="btn btn-outline mx-auto mt-10 block" onClick={()=>setVisible(v=>v+24)}>Load more</button>}</>:<div className="rounded-xl border border-line bg-white px-6 py-16 text-center"><h2 className="font-display text-3xl text-ink">Nothing matched those filters</h2><p className="mt-2 text-muted">Try widening your search or explore the complete collection.</p><button className="btn btn-gold mt-6" onClick={clear}>Clear filters</button></div>}</section></div></main>;
}
